### ISSUE TITLE
Ubuntu build fails since KLUSolve requiring CMake >=3.18

### ISSUE THREAD

**Issue by djmulcahy** [beroset/docker_dss#5]
### Summary
Using Docker to build the Ubuntu-based image from `Dockerfile.ubuntu` fails. `KLUSolve` cannot be build because the newest version (since ~ Jan 2021), requires `CMake` >= 3.18. The standard repository for 20.04 (Ubuntu:focal) has an older version. 

### Code to reproduce the issue

Using Docker, I used the following code to build the container from main direcotry of the repo:
`docker build . -f ./work/Dockerfile.ubuntu`

The code produces the following error:

```
...
-Wall -O3 -DREAD_KUNDERT -I../../Include -o klu_simple.o -c klu_simple.cmake_minimum_required
#18 8.342 gcc klu_simple.o -L../../Lib -Bstatic -lklu -lamd -lbtf -lcolamd -lcsparse -lczsparse -lm -o ../../Test/KLDemo.exe
#18  8.378 make[2]: Leaving directory '/tmp/KLUSolve/KLU/Demo'
#18 8.378 make[1]: Leaving directory '/tmp/KLUSolve'
#18 8.378 mkdir -p linenoise-ng/build
#18 8.379 cd linenoise-ng/build && cmake -DCMAKE_BUILD_TYPE=Release ..
#18 8.478 CMake Error at CMakeLists.txt:3 (cmake_minimum_required):
#18 8.478   CMake 3.18 or higher is required.  You are running version 3.16.3
```

### Notes

This issue or similar may be present in other Dockerfiles as well.

### Potential Solution

Download and install a later version of cMake directly from [official CMake website](https://cmake.org/download/) in the docker image.

**Comment by beroset** [comment]
Thanks for the PR!
